export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const UPDATE_REQUEST = "UPDATE_REQUEST";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_ERROR = "DELETE_ERROR";
